#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AI_Pterodactylus_Controller

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "TheIsle_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AI_Pterodactylus_Controller.BP_AI_Pterodactylus_Controller_C
// 0x0008 (0x07A8 - 0x07A0)
class ABP_AI_Pterodactylus_Controller_C final : public ATIAIFlyingScavengerController
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x07A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_BP_AI_Pterodactylus_Controller(int32 EntryPoint);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AI_Pterodactylus_Controller_C">();
	}
	static class ABP_AI_Pterodactylus_Controller_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AI_Pterodactylus_Controller_C>();
	}
};
static_assert(alignof(ABP_AI_Pterodactylus_Controller_C) == 0x000008, "Wrong alignment on ABP_AI_Pterodactylus_Controller_C");
static_assert(sizeof(ABP_AI_Pterodactylus_Controller_C) == 0x0007A8, "Wrong size on ABP_AI_Pterodactylus_Controller_C");
static_assert(offsetof(ABP_AI_Pterodactylus_Controller_C, UberGraphFrame) == 0x0007A0, "Member 'ABP_AI_Pterodactylus_Controller_C::UberGraphFrame' has a wrong offset!");

}

