#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UMG_ReplayMenuRow

#include "Basic.hpp"

#include "BP_UMG_ReplayMenuRow_classes.hpp"
#include "BP_UMG_ReplayMenuRow_parameters.hpp"


namespace SDK
{

// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.BndEvt__BP_UMG_ReplayMenuRow_ReplayName_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// ETextCommit                             CommitMethod                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UMG_ReplayMenuRow_C::BndEvt__BP_UMG_ReplayMenuRow_ReplayName_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "BndEvt__BP_UMG_ReplayMenuRow_ReplayName_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature");

	Params::BP_UMG_ReplayMenuRow_C_BndEvt__BP_UMG_ReplayMenuRow_ReplayName_K2Node_ComponentBoundEvent_1_OnEditableTextBoxCommittedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);
	Parms.CommitMethod = CommitMethod;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.BndEvt__Button_Select_K2Node_ComponentBoundEvent_75_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UBP_UMG_ReplayMenuRow_C::BndEvt__Button_Select_K2Node_ComponentBoundEvent_75_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "BndEvt__Button_Select_K2Node_ComponentBoundEvent_75_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UBP_UMG_ReplayMenuRow_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.ExecuteUbergraph_BP_UMG_ReplayMenuRow
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UMG_ReplayMenuRow_C::ExecuteUbergraph_BP_UMG_ReplayMenuRow(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "ExecuteUbergraph_BP_UMG_ReplayMenuRow");

	Params::BP_UMG_ReplayMenuRow_C_ExecuteUbergraph_BP_UMG_ReplayMenuRow Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.SetRenameFocus
// (BlueprintCallable, BlueprintEvent)

void UBP_UMG_ReplayMenuRow_C::SetRenameFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "SetRenameFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.SetSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Selected                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UMG_ReplayMenuRow_C::SetSelected(bool Selected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "SetSelected");

	Params::BP_UMG_ReplayMenuRow_C_SetSelected Parms{};

	Parms.Selected = Selected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.Setup
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Replay_Index                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FDemoEntry&                Replay_Data_0                                          (BlueprintVisible, BlueprintReadOnly, Parm)
// class UBP_UMG_ReplayMenu_C*             Parent_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UBP_UMG_ReplayMenuRow_C::Setup(int32 Replay_Index, const struct FDemoEntry& Replay_Data_0, class UBP_UMG_ReplayMenu_C* Parent_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "Setup");

	Params::BP_UMG_ReplayMenuRow_C_Setup Parms{};

	Parms.Replay_Index = Replay_Index;
	Parms.Replay_Data_0 = std::move(Replay_Data_0);
	Parms.Parent_0 = Parent_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.TextUpdate
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UBP_UMG_ReplayMenuRow_C::TextUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "TextUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_UMG_ReplayMenuRow.BP_UMG_ReplayMenuRow_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_UMG_ReplayMenuRow_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_UMG_ReplayMenuRow_C", "Tick");

	Params::BP_UMG_ReplayMenuRow_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

