#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Bleeding

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "TheIsle_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function GC_Bleeding.GC_Bleeding_C.OnExecute
// 0x0540 (0x0540 - 0x0000)
struct GC_Bleeding_C_OnExecute final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00D8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	bool                                          ReturnValue;                                       // 0x00E0(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E1[0x3];                                       // 0x00E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATICharacterBase*                       K2Node_DynamicCast_AsThe_Isle_Character_Base;      // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATIHumanBase*                           K2Node_DynamicCast_AsThe_Isle_Human_Base;          // 0x00F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_101[0x7];                                      // 0x0101(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0108(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x0120(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATICharacterBase*                       CallFunc_GetDraggerCarrier_ReturnValue;            // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0140(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSwimming_ReturnValue;                   // 0x0149(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAbilityState                                 CallFunc_GetAbilityState_ReturnValue;              // 0x014A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x014B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x014C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsFlying_ReturnValue;                     // 0x014D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsUnderwater_ReturnValue;                 // 0x014E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSwimming_ReturnValue_1;                 // 0x014F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x0151(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_152[0x2];                                      // 0x0152(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_GetScaledCapsuleHalfHeight_ReturnValue;   // 0x0154(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_2;                  // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_159[0x7];                                      // 0x0159(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_3;                  // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_4;                  // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16A[0x6];                                      // 0x016A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0178(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_GetScaledCapsuleRadius_ReturnValue;       // 0x0190(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_194[0x4];                                      // 0x0194(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue_1;        // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBleedingClogged_ReturnValue;            // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A9[0x7];                                      // 0x01A9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATIDinosaurBase*                        K2Node_DynamicCast_AsThe_Isle_Dinosaur_Base;       // 0x01B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsGodMode_ReturnValue;                    // 0x01B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x01BA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1BB[0x1];                                      // 0x01BB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x01BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsAlive_ReturnValue;                   // 0x01C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C2[0x6];                                      // 0x01C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue_1;          // 0x01C8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         K2Node_MakeArray_Array;                            // 0x01E0(0x0010)(ConstParm, ReferenceParm)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x01F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0208(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0220(0x00F8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0318(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x0319(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x031A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31B[0x1];                                      // 0x031B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakHitResult_Time;                      // 0x031C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x0320(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_324[0x4];                                      // 0x0324(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x0328(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x0340(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x0358(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x0370(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0388(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0390(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0398(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x03A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x03A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x03B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x03B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x03B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3BC[0x4];                                      // 0x03BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x03C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x03D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_Conv_VectorToRotator_ReturnValue;         // 0x03F0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0408(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_409[0x3];                                      // 0x0409(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BreakRotator_Roll;                        // 0x040C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0410(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0414(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0418(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue_1;      // 0x0420(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x0438(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue_1;      // 0x0450(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_458[0x8];                                      // 0x0458(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x0460(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentScale_ReturnValue;         // 0x04C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x04D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorFloat_ReturnValue;              // 0x04E0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_ClampVectorSize_ReturnValue;              // 0x04F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_BloodSplat_C*                       CallFunc_FinishSpawningActor_ReturnValue;          // 0x0510(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_A_ImplicitCast;       // 0x0518(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Yaw_ImplicitCast;             // 0x0520(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_524[0x4];                                      // 0x0524(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0528(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_A_ImplicitCast;     // 0x0530(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Pitch_ImplicitCast;           // 0x0538(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GC_Bleeding_C_OnExecute) == 0x000010, "Wrong alignment on GC_Bleeding_C_OnExecute");
static_assert(sizeof(GC_Bleeding_C_OnExecute) == 0x000540, "Wrong size on GC_Bleeding_C_OnExecute");
static_assert(offsetof(GC_Bleeding_C_OnExecute, MyTarget) == 0x000000, "Member 'GC_Bleeding_C_OnExecute::MyTarget' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, Parameters) == 0x000008, "Member 'GC_Bleeding_C_OnExecute::Parameters' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, ReturnValue) == 0x0000E0, "Member 'GC_Bleeding_C_OnExecute::ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, Temp_int_Variable) == 0x0000E4, "Member 'GC_Bleeding_C_OnExecute::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, K2Node_DynamicCast_AsThe_Isle_Character_Base) == 0x0000E8, "Member 'GC_Bleeding_C_OnExecute::K2Node_DynamicCast_AsThe_Isle_Character_Base' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, K2Node_DynamicCast_bSuccess) == 0x0000F0, "Member 'GC_Bleeding_C_OnExecute::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, K2Node_DynamicCast_AsThe_Isle_Human_Base) == 0x0000F8, "Member 'GC_Bleeding_C_OnExecute::K2Node_DynamicCast_AsThe_Isle_Human_Base' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, K2Node_DynamicCast_bSuccess_1) == 0x000100, "Member 'GC_Bleeding_C_OnExecute::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_MakeVector_ReturnValue) == 0x000108, "Member 'GC_Bleeding_C_OnExecute::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_GetSocketLocation_ReturnValue) == 0x000120, "Member 'GC_Bleeding_C_OnExecute::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_GetDraggerCarrier_ReturnValue) == 0x000138, "Member 'GC_Bleeding_C_OnExecute::CallFunc_GetDraggerCarrier_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x000140, "Member 'GC_Bleeding_C_OnExecute::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_IsValid_ReturnValue) == 0x000148, "Member 'GC_Bleeding_C_OnExecute::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_IsSwimming_ReturnValue) == 0x000149, "Member 'GC_Bleeding_C_OnExecute::CallFunc_IsSwimming_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_GetAbilityState_ReturnValue) == 0x00014A, "Member 'GC_Bleeding_C_OnExecute::CallFunc_GetAbilityState_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_IsValid_ReturnValue_1) == 0x00014B, "Member 'GC_Bleeding_C_OnExecute::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00014C, "Member 'GC_Bleeding_C_OnExecute::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_IsFlying_ReturnValue) == 0x00014D, "Member 'GC_Bleeding_C_OnExecute::CallFunc_IsFlying_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_IsUnderwater_ReturnValue) == 0x00014E, "Member 'GC_Bleeding_C_OnExecute::CallFunc_IsUnderwater_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_IsSwimming_ReturnValue_1) == 0x00014F, "Member 'GC_Bleeding_C_OnExecute::CallFunc_IsSwimming_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BooleanOR_ReturnValue) == 0x000150, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BooleanOR_ReturnValue_1) == 0x000151, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BooleanOR_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_GetScaledCapsuleHalfHeight_ReturnValue) == 0x000154, "Member 'GC_Bleeding_C_OnExecute::CallFunc_GetScaledCapsuleHalfHeight_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BooleanOR_ReturnValue_2) == 0x000158, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BooleanOR_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000160, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BooleanOR_ReturnValue_3) == 0x000168, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BooleanOR_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BooleanOR_ReturnValue_4) == 0x000169, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BooleanOR_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_RandomFloatInRange_ReturnValue) == 0x000170, "Member 'GC_Bleeding_C_OnExecute::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_MakeRotator_ReturnValue) == 0x000178, "Member 'GC_Bleeding_C_OnExecute::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_GetScaledCapsuleRadius_ReturnValue) == 0x000190, "Member 'GC_Bleeding_C_OnExecute::CallFunc_GetScaledCapsuleRadius_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000198, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Divide_DoubleDouble_ReturnValue_1) == 0x0001A0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Divide_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_IsBleedingClogged_ReturnValue) == 0x0001A8, "Member 'GC_Bleeding_C_OnExecute::CallFunc_IsBleedingClogged_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, K2Node_DynamicCast_AsThe_Isle_Dinosaur_Base) == 0x0001B0, "Member 'GC_Bleeding_C_OnExecute::K2Node_DynamicCast_AsThe_Isle_Dinosaur_Base' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, K2Node_DynamicCast_bSuccess_2) == 0x0001B8, "Member 'GC_Bleeding_C_OnExecute::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_IsGodMode_ReturnValue) == 0x0001B9, "Member 'GC_Bleeding_C_OnExecute::CallFunc_IsGodMode_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x0001BA, "Member 'GC_Bleeding_C_OnExecute::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Add_IntInt_ReturnValue) == 0x0001BC, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x0001C0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_GetIsAlive_ReturnValue) == 0x0001C1, "Member 'GC_Bleeding_C_OnExecute::CallFunc_GetIsAlive_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_GetSocketLocation_ReturnValue_1) == 0x0001C8, "Member 'GC_Bleeding_C_OnExecute::CallFunc_GetSocketLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, K2Node_MakeArray_Array) == 0x0001E0, "Member 'GC_Bleeding_C_OnExecute::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Add_VectorVector_ReturnValue) == 0x0001F0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000208, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_LineTraceSingle_OutHit) == 0x000220, "Member 'GC_Bleeding_C_OnExecute::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_LineTraceSingle_ReturnValue) == 0x000318, "Member 'GC_Bleeding_C_OnExecute::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_bBlockingHit) == 0x000319, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_bBlockingHit' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_bInitialOverlap) == 0x00031A, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_bInitialOverlap' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_Time) == 0x00031C, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_Time' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_Distance) == 0x000320, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_Distance' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_Location) == 0x000328, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_Location' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_ImpactPoint) == 0x000340, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_ImpactPoint' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_Normal) == 0x000358, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_Normal' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_ImpactNormal) == 0x000370, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_ImpactNormal' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_PhysMat) == 0x000388, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_PhysMat' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_HitActor) == 0x000390, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_HitActor' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_HitComponent) == 0x000398, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_HitComponent' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_HitBoneName) == 0x0003A0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_HitBoneName' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_BoneName) == 0x0003A8, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_BoneName' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_HitItem) == 0x0003B0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_HitItem' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_ElementIndex) == 0x0003B4, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_ElementIndex' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_FaceIndex) == 0x0003B8, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_FaceIndex' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_TraceStart) == 0x0003C0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_TraceStart' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakHitResult_TraceEnd) == 0x0003D8, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakHitResult_TraceEnd' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Conv_VectorToRotator_ReturnValue) == 0x0003F0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Conv_VectorToRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x000408, "Member 'GC_Bleeding_C_OnExecute::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakRotator_Roll) == 0x00040C, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakRotator_Pitch) == 0x000410, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BreakRotator_Yaw) == 0x000414, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000418, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Subtract_VectorVector_ReturnValue_1) == 0x000420, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Subtract_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_MakeRotator_ReturnValue_1) == 0x000438, "Member 'GC_Bleeding_C_OnExecute::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_SpawnSystemAtLocation_ReturnValue_1) == 0x000450, "Member 'GC_Bleeding_C_OnExecute::CallFunc_SpawnSystemAtLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_MakeTransform_ReturnValue) == 0x000460, "Member 'GC_Bleeding_C_OnExecute::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_K2_GetComponentScale_ReturnValue) == 0x0004C0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_K2_GetComponentScale_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x0004D8, "Member 'GC_Bleeding_C_OnExecute::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Add_VectorFloat_ReturnValue) == 0x0004E0, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Add_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_ClampVectorSize_ReturnValue) == 0x0004F8, "Member 'GC_Bleeding_C_OnExecute::CallFunc_ClampVectorSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_FinishSpawningActor_ReturnValue) == 0x000510, "Member 'GC_Bleeding_C_OnExecute::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Divide_DoubleDouble_A_ImplicitCast) == 0x000518, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Divide_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_MakeRotator_Yaw_ImplicitCast) == 0x000520, "Member 'GC_Bleeding_C_OnExecute::CallFunc_MakeRotator_Yaw_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000528, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_Subtract_DoubleDouble_A_ImplicitCast) == 0x000530, "Member 'GC_Bleeding_C_OnExecute::CallFunc_Subtract_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(GC_Bleeding_C_OnExecute, CallFunc_MakeRotator_Pitch_ImplicitCast) == 0x000538, "Member 'GC_Bleeding_C_OnExecute::CallFunc_MakeRotator_Pitch_ImplicitCast' has a wrong offset!");

}

