#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_ForcePouncerFixRotation

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_ForcePouncerFixRotation.GC_ForcePouncerFixRotation_C
// 0x0008 (0x0308 - 0x0300)
class AGC_ForcePouncerFixRotation_C final : public AGameplayCueNotify_Actor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0300(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GC_ForcePouncerFixRotation_C">();
	}
	static class AGC_ForcePouncerFixRotation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGC_ForcePouncerFixRotation_C>();
	}
};
static_assert(alignof(AGC_ForcePouncerFixRotation_C) == 0x000008, "Wrong alignment on AGC_ForcePouncerFixRotation_C");
static_assert(sizeof(AGC_ForcePouncerFixRotation_C) == 0x000308, "Wrong size on AGC_ForcePouncerFixRotation_C");
static_assert(offsetof(AGC_ForcePouncerFixRotation_C, DefaultSceneRoot) == 0x000300, "Member 'AGC_ForcePouncerFixRotation_C::DefaultSceneRoot' has a wrong offset!");

}

