#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Keybinds

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function WBP_Keybinds.WBP_Keybinds_C.DirtyCheck
// 0x0004 (0x0004 - 0x0000)
struct WBP_Keybinds_C_DirtyCheck final
{
public:
	bool                                          bIsDirty_0;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_BoolBool_ReturnValue;          // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_BoolBool_ReturnValue_1;        // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_BoolBool_ReturnValue_2;        // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Keybinds_C_DirtyCheck) == 0x000001, "Wrong alignment on WBP_Keybinds_C_DirtyCheck");
static_assert(sizeof(WBP_Keybinds_C_DirtyCheck) == 0x000004, "Wrong size on WBP_Keybinds_C_DirtyCheck");
static_assert(offsetof(WBP_Keybinds_C_DirtyCheck, bIsDirty_0) == 0x000000, "Member 'WBP_Keybinds_C_DirtyCheck::bIsDirty_0' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_DirtyCheck, CallFunc_EqualEqual_BoolBool_ReturnValue) == 0x000001, "Member 'WBP_Keybinds_C_DirtyCheck::CallFunc_EqualEqual_BoolBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_DirtyCheck, CallFunc_EqualEqual_BoolBool_ReturnValue_1) == 0x000002, "Member 'WBP_Keybinds_C_DirtyCheck::CallFunc_EqualEqual_BoolBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_DirtyCheck, CallFunc_EqualEqual_BoolBool_ReturnValue_2) == 0x000003, "Member 'WBP_Keybinds_C_DirtyCheck::CallFunc_EqualEqual_BoolBool_ReturnValue_2' has a wrong offset!");

// Function WBP_Keybinds.WBP_Keybinds_C.ExecuteUbergraph_WBP_Keybinds
// 0x0288 (0x0288 - 0x0000)
struct WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Keybinding_C*                      CallFunc_Create_ReturnValue;                       // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_HorizontalMouseSensitivity_C*      CallFunc_Create_ReturnValue_1;                     // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UWBP_VerticalMouseSensitivity_C*        CallFunc_Create_ReturnValue_2;                     // 0x0018(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_24[0x4];                                       // 0x0024(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue;                     // 0x0028(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_Keybinding_C*                      CallFunc_Create_ReturnValue_3;                     // 0x0038(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWBP_Keybinding_C*                      CallFunc_Create_ReturnValue_4;                     // 0x0050(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x005C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_Keybinding_C*                      CallFunc_Create_ReturnValue_5;                     // 0x0070(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x0078(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_5;                   // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_5;                  // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_6;                   // 0x0090(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_6;                  // 0x0094(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_7;                  // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_7;                 // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A4[0x4];                                       // 0x00A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_1;                   // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_2;                   // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_7;                   // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_3;                   // 0x00C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_4;                   // 0x00C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue;             // 0x00D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetActionNames_ActionNames;               // 0x00D8(0x0010)(ReferenceParm)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CallFunc_Array_Get_Item;                           // 0x00EC(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F4[0x4];                                       // 0x00F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FInputActionKeyMapping>         CallFunc_GetActionMappingByName_OutMappings;       // 0x00F8(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0108(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10C[0x4];                                      // 0x010C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionKeyMapping                 CallFunc_Array_Get_Item_1;                         // 0x0110(0x0028)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_139[0x3];                                      // 0x0139(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue;             // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0141(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_142[0x6];                                      // 0x0142(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_1;           // 0x0148(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetAxisNames_AxisNames;                   // 0x0150(0x0010)(ReferenceParm)
	TArray<class FName>                           CallFunc_GetActionNames_ActionNames_1;             // 0x0160(0x0010)(ReferenceParm)
	class FName                                   CallFunc_Array_Get_Item_2;                         // 0x0170(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item_3;                         // 0x0178(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FInputAxisKeyMapping>           CallFunc_GetAxisMappingByName_OutMappings;         // 0x0180(0x0010)(ReferenceParm)
	TArray<struct FInputActionKeyMapping>         CallFunc_GetActionMappingByName_OutMappings_1;     // 0x0190(0x0010)(ReferenceParm)
	struct FInputAxisKeyMapping                   CallFunc_Array_Get_Item_4;                         // 0x01A0(0x0028)()
	struct FInputActionKeyMapping                 CallFunc_Array_Get_Item_5;                         // 0x01C8(0x0028)()
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue_1;           // 0x01F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue_2;           // 0x01F1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1F2[0x2];                                      // 0x01F2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x01F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x01F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x01FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x01FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1FE[0x2];                                      // 0x01FE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x0200(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x0204(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x0209(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_20A[0x6];                                      // 0x020A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_2;           // 0x0210(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetAxisNames_AxisNames_1;                 // 0x0218(0x0010)(ReferenceParm)
	class UPanelSlot*                             CallFunc_AddChild_ReturnValue_5;                   // 0x0228(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item_6;                         // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_6;               // 0x0238(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23C[0x4];                                      // 0x023C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FInputAxisKeyMapping>           CallFunc_GetAxisMappingByName_OutMappings_1;       // 0x0240(0x0010)(ReferenceParm)
	bool                                          CallFunc_Less_IntInt_ReturnValue_6;                // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputAxisKeyMapping                   CallFunc_Array_Get_Item_7;                         // 0x0258(0x0028)()
	int32                                         CallFunc_Array_Length_ReturnValue_7;               // 0x0280(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue_3;           // 0x0284(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_7;                // 0x0285(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds) == 0x000008, "Wrong alignment on WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds");
static_assert(sizeof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds) == 0x000288, "Wrong size on WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, EntryPoint) == 0x000000, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Create_ReturnValue) == 0x000008, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Create_ReturnValue_1) == 0x000010, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Create_ReturnValue_2) == 0x000018, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Loop_Counter_Variable) == 0x000020, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_AddChild_ReturnValue) == 0x000028, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_AddChild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Add_IntInt_ReturnValue) == 0x000030, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Array_Index_Variable) == 0x000034, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Create_ReturnValue_3) == 0x000038, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Create_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Array_Index_Variable_1) == 0x000040, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Loop_Counter_Variable_1) == 0x000044, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Add_IntInt_ReturnValue_1) == 0x000048, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Array_Index_Variable_2) == 0x00004C, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Create_ReturnValue_4) == 0x000050, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Create_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Loop_Counter_Variable_2) == 0x000058, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Loop_Counter_Variable_3) == 0x00005C, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Add_IntInt_ReturnValue_2) == 0x000060, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Add_IntInt_ReturnValue_3) == 0x000064, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Array_Index_Variable_3) == 0x000068, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Create_ReturnValue_5) == 0x000070, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Create_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Array_Index_Variable_4) == 0x000078, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Loop_Counter_Variable_4) == 0x00007C, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Add_IntInt_ReturnValue_4) == 0x000080, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Array_Index_Variable_5) == 0x000084, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Array_Index_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Loop_Counter_Variable_5) == 0x000088, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Loop_Counter_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Add_IntInt_ReturnValue_5) == 0x00008C, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Array_Index_Variable_6) == 0x000090, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Array_Index_Variable_6' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Loop_Counter_Variable_6) == 0x000094, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Loop_Counter_Variable_6' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Add_IntInt_ReturnValue_6) == 0x000098, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Add_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Loop_Counter_Variable_7) == 0x00009C, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Loop_Counter_Variable_7' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Add_IntInt_ReturnValue_7) == 0x0000A0, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Add_IntInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_AddChild_ReturnValue_1) == 0x0000A8, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_AddChild_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_AddChild_ReturnValue_2) == 0x0000B0, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_AddChild_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, Temp_int_Array_Index_Variable_7) == 0x0000B8, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::Temp_int_Array_Index_Variable_7' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_AddChild_ReturnValue_3) == 0x0000C0, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_AddChild_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_AddChild_ReturnValue_4) == 0x0000C8, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_AddChild_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetInputSettings_ReturnValue) == 0x0000D0, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetInputSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetActionNames_ActionNames) == 0x0000D8, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetActionNames_ActionNames' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_IsValid_ReturnValue) == 0x0000E8, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Get_Item) == 0x0000EC, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetActionMappingByName_OutMappings) == 0x0000F8, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetActionMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Length_ReturnValue) == 0x000108, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Get_Item_1) == 0x000110, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Less_IntInt_ReturnValue) == 0x000138, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Length_ReturnValue_1) == 0x00013C, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Key_IsGamepadKey_ReturnValue) == 0x000140, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Key_IsGamepadKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Less_IntInt_ReturnValue_1) == 0x000141, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetInputSettings_ReturnValue_1) == 0x000148, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetInputSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetAxisNames_AxisNames) == 0x000150, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetAxisNames_AxisNames' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetActionNames_ActionNames_1) == 0x000160, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetActionNames_ActionNames_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Get_Item_2) == 0x000170, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Get_Item_3) == 0x000178, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetAxisMappingByName_OutMappings) == 0x000180, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetAxisMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetActionMappingByName_OutMappings_1) == 0x000190, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetActionMappingByName_OutMappings_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Get_Item_4) == 0x0001A0, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Get_Item_5) == 0x0001C8, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Key_IsGamepadKey_ReturnValue_1) == 0x0001F0, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Key_IsGamepadKey_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Key_IsGamepadKey_ReturnValue_2) == 0x0001F1, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Key_IsGamepadKey_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Length_ReturnValue_2) == 0x0001F4, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Length_ReturnValue_3) == 0x0001F8, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Less_IntInt_ReturnValue_2) == 0x0001FC, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Less_IntInt_ReturnValue_3) == 0x0001FD, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Length_ReturnValue_4) == 0x000200, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Length_ReturnValue_5) == 0x000204, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Less_IntInt_ReturnValue_4) == 0x000208, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Less_IntInt_ReturnValue_5) == 0x000209, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetInputSettings_ReturnValue_2) == 0x000210, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetInputSettings_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetAxisNames_AxisNames_1) == 0x000218, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetAxisNames_AxisNames_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_AddChild_ReturnValue_5) == 0x000228, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_AddChild_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Get_Item_6) == 0x000230, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Length_ReturnValue_6) == 0x000238, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Length_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_GetAxisMappingByName_OutMappings_1) == 0x000240, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_GetAxisMappingByName_OutMappings_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Less_IntInt_ReturnValue_6) == 0x000250, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Less_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Get_Item_7) == 0x000258, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Get_Item_7' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Array_Length_ReturnValue_7) == 0x000280, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Array_Length_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Key_IsGamepadKey_ReturnValue_3) == 0x000284, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Key_IsGamepadKey_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds, CallFunc_Less_IntInt_ReturnValue_7) == 0x000285, "Member 'WBP_Keybinds_C_ExecuteUbergraph_WBP_Keybinds::CallFunc_Less_IntInt_ReturnValue_7' has a wrong offset!");

// Function WBP_Keybinds.WBP_Keybinds_C.GetSavedControlSettings
// 0x0004 (0x0004 - 0x0000)
struct WBP_Keybinds_C_GetSavedControlSettings final
{
public:
	bool                                          CallFunc_GetControlsSettings_bInvertLookX;         // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetControlsSettings_bInvertLookY;         // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetControlsSettings_bRumble;              // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetControlsSettings_ReturnValue;          // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Keybinds_C_GetSavedControlSettings) == 0x000001, "Wrong alignment on WBP_Keybinds_C_GetSavedControlSettings");
static_assert(sizeof(WBP_Keybinds_C_GetSavedControlSettings) == 0x000004, "Wrong size on WBP_Keybinds_C_GetSavedControlSettings");
static_assert(offsetof(WBP_Keybinds_C_GetSavedControlSettings, CallFunc_GetControlsSettings_bInvertLookX) == 0x000000, "Member 'WBP_Keybinds_C_GetSavedControlSettings::CallFunc_GetControlsSettings_bInvertLookX' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_GetSavedControlSettings, CallFunc_GetControlsSettings_bInvertLookY) == 0x000001, "Member 'WBP_Keybinds_C_GetSavedControlSettings::CallFunc_GetControlsSettings_bInvertLookY' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_GetSavedControlSettings, CallFunc_GetControlsSettings_bRumble) == 0x000002, "Member 'WBP_Keybinds_C_GetSavedControlSettings::CallFunc_GetControlsSettings_bRumble' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_GetSavedControlSettings, CallFunc_GetControlsSettings_ReturnValue) == 0x000003, "Member 'WBP_Keybinds_C_GetSavedControlSettings::CallFunc_GetControlsSettings_ReturnValue' has a wrong offset!");

// Function WBP_Keybinds.WBP_Keybinds_C.MarkControlsAsDirty
// 0x0001 (0x0001 - 0x0000)
struct WBP_Keybinds_C_MarkControlsAsDirty final
{
public:
	bool                                          CallFunc_DirtyCheck_bIsDirty;                      // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Keybinds_C_MarkControlsAsDirty) == 0x000001, "Wrong alignment on WBP_Keybinds_C_MarkControlsAsDirty");
static_assert(sizeof(WBP_Keybinds_C_MarkControlsAsDirty) == 0x000001, "Wrong size on WBP_Keybinds_C_MarkControlsAsDirty");
static_assert(offsetof(WBP_Keybinds_C_MarkControlsAsDirty, CallFunc_DirtyCheck_bIsDirty) == 0x000000, "Member 'WBP_Keybinds_C_MarkControlsAsDirty::CallFunc_DirtyCheck_bIsDirty' has a wrong offset!");

// Function WBP_Keybinds.WBP_Keybinds_C.RemoveActionMappingByName
// 0x0070 (0x0070 - 0x0000)
struct WBP_Keybinds_C_RemoveActionMappingByName final
{
public:
	class FName                                   InActionName;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bGamepadMapping;                                   // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bLocalGamepadMapping;                              // 0x0009(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue;             // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_1;           // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FInputActionKeyMapping>         CallFunc_GetActionMappingByName_OutMappings;       // 0x0028(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3C[0x4];                                       // 0x003C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionKeyMapping                 CallFunc_Array_Get_Item;                           // 0x0040(0x0028)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue;             // 0x0069(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_BoolBool_ReturnValue;          // 0x006A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Keybinds_C_RemoveActionMappingByName) == 0x000008, "Wrong alignment on WBP_Keybinds_C_RemoveActionMappingByName");
static_assert(sizeof(WBP_Keybinds_C_RemoveActionMappingByName) == 0x000070, "Wrong size on WBP_Keybinds_C_RemoveActionMappingByName");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, InActionName) == 0x000000, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::InActionName' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, bGamepadMapping) == 0x000008, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::bGamepadMapping' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, bLocalGamepadMapping) == 0x000009, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::bLocalGamepadMapping' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, Temp_int_Loop_Counter_Variable) == 0x000010, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_Add_IntInt_ReturnValue) == 0x000014, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_GetInputSettings_ReturnValue) == 0x000018, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_GetInputSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_GetInputSettings_ReturnValue_1) == 0x000020, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_GetInputSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_GetActionMappingByName_OutMappings) == 0x000028, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_GetActionMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_Array_Get_Item) == 0x000040, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_Less_IntInt_ReturnValue) == 0x000068, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_Key_IsGamepadKey_ReturnValue) == 0x000069, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_Key_IsGamepadKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveActionMappingByName, CallFunc_EqualEqual_BoolBool_ReturnValue) == 0x00006A, "Member 'WBP_Keybinds_C_RemoveActionMappingByName::CallFunc_EqualEqual_BoolBool_ReturnValue' has a wrong offset!");

// Function WBP_Keybinds.WBP_Keybinds_C.RemoveAxisMappingByName
// 0x0088 (0x0088 - 0x0000)
struct WBP_Keybinds_C_RemoveAxisMappingByName final
{
public:
	class FName                                   InAxisName;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsGamepadMapping;                                 // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Scale;                                             // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bLocalGamepadMapping;                              // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue;             // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_1;           // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FInputAxisKeyMapping>           CallFunc_GetAxisMappingByName_OutMappings;         // 0x0038(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputAxisKeyMapping                   CallFunc_Array_Get_Item;                           // 0x0050(0x0028)()
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue;             // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_BoolBool_ReturnValue;          // 0x007B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Keybinds_C_RemoveAxisMappingByName) == 0x000008, "Wrong alignment on WBP_Keybinds_C_RemoveAxisMappingByName");
static_assert(sizeof(WBP_Keybinds_C_RemoveAxisMappingByName) == 0x000088, "Wrong size on WBP_Keybinds_C_RemoveAxisMappingByName");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, InAxisName) == 0x000000, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::InAxisName' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, bIsGamepadMapping) == 0x000008, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::bIsGamepadMapping' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, Scale) == 0x000010, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::Scale' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, bLocalGamepadMapping) == 0x000018, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::bLocalGamepadMapping' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, Temp_int_Array_Index_Variable) == 0x00001C, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, Temp_int_Loop_Counter_Variable) == 0x000020, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_Add_IntInt_ReturnValue) == 0x000024, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_GetInputSettings_ReturnValue) == 0x000028, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_GetInputSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_GetInputSettings_ReturnValue_1) == 0x000030, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_GetInputSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_GetAxisMappingByName_OutMappings) == 0x000038, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_GetAxisMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_Array_Length_ReturnValue) == 0x000048, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_Array_Get_Item) == 0x000050, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_Less_IntInt_ReturnValue) == 0x000078, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_Key_IsGamepadKey_ReturnValue) == 0x000079, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_Key_IsGamepadKey_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_EqualEqual_DoubleDouble_ReturnValue) == 0x00007A, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_EqualEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_EqualEqual_BoolBool_ReturnValue) == 0x00007B, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_EqualEqual_BoolBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_RemoveAxisMappingByName, CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast) == 0x000080, "Member 'WBP_Keybinds_C_RemoveAxisMappingByName::CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");

// Function WBP_Keybinds.WBP_Keybinds_C.ResetKeybindings
// 0x01C0 (0x01C0 - 0x0000)
struct WBP_Keybinds_C_ResetKeybindings final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_5;                  // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue;             // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_1;           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_5;                   // 0x0058(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_2;           // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_3;           // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_4;           // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_5;           // 0x0078(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetAxisNames_AxisNames;                   // 0x0080(0x0010)(ReferenceParm)
	TArray<class FName>                           CallFunc_GetActionNames_ActionNames;               // 0x0090(0x0010)(ReferenceParm)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item_1;                         // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FInputAxisKeyMapping>           CallFunc_GetAxisMappingByName_OutMappings;         // 0x00B0(0x0010)(ReferenceParm)
	TArray<struct FInputActionKeyMapping>         CallFunc_GetActionMappingByName_OutMappings;       // 0x00C0(0x0010)(ReferenceParm)
	struct FInputAxisKeyMapping                   CallFunc_Array_Get_Item_2;                         // 0x00D0(0x0028)()
	struct FInputActionKeyMapping                 CallFunc_Array_Get_Item_3;                         // 0x00F8(0x0028)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0129(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_12A[0x2];                                      // 0x012A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0130(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0134(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0135(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_136[0x2];                                      // 0x0136(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_6;           // 0x0138(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<struct FInputAxisKeyMapping>           CallFunc_GetDefaultAxisMappings_ReturnValue;       // 0x0140(0x0010)(ReferenceParm)
	TArray<struct FInputActionKeyMapping>         CallFunc_GetDefaultActionMappings_ReturnValue;     // 0x0150(0x0010)(ReferenceParm)
	struct FInputAxisKeyMapping                   CallFunc_Array_Get_Item_4;                         // 0x0160(0x0028)()
	struct FInputActionKeyMapping                 CallFunc_Array_Get_Item_5;                         // 0x0188(0x0028)()
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x01B4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x01B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x01B9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Keybinds_C_ResetKeybindings) == 0x000008, "Wrong alignment on WBP_Keybinds_C_ResetKeybindings");
static_assert(sizeof(WBP_Keybinds_C_ResetKeybindings) == 0x0001C0, "Wrong size on WBP_Keybinds_C_ResetKeybindings");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Loop_Counter_Variable_1) == 0x00000C, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Add_IntInt_ReturnValue_1) == 0x000010, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Array_Index_Variable_1) == 0x000014, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Array_Index_Variable_2) == 0x000018, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Loop_Counter_Variable_2) == 0x00001C, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Add_IntInt_ReturnValue_2) == 0x000020, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Array_Index_Variable_3) == 0x000024, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Loop_Counter_Variable_3) == 0x000028, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Loop_Counter_Variable_4) == 0x00002C, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Add_IntInt_ReturnValue_3) == 0x000030, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Add_IntInt_ReturnValue_4) == 0x000034, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Loop_Counter_Variable_5) == 0x000038, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Loop_Counter_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Add_IntInt_ReturnValue_5) == 0x00003C, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Array_Index_Variable_4) == 0x000040, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetInputSettings_ReturnValue) == 0x000048, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetInputSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetInputSettings_ReturnValue_1) == 0x000050, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetInputSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, Temp_int_Array_Index_Variable_5) == 0x000058, "Member 'WBP_Keybinds_C_ResetKeybindings::Temp_int_Array_Index_Variable_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetInputSettings_ReturnValue_2) == 0x000060, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetInputSettings_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetInputSettings_ReturnValue_3) == 0x000068, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetInputSettings_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetInputSettings_ReturnValue_4) == 0x000070, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetInputSettings_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetInputSettings_ReturnValue_5) == 0x000078, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetInputSettings_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetAxisNames_AxisNames) == 0x000080, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetAxisNames_AxisNames' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetActionNames_ActionNames) == 0x000090, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetActionNames_ActionNames' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Get_Item) == 0x0000A0, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Get_Item_1) == 0x0000A8, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetAxisMappingByName_OutMappings) == 0x0000B0, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetAxisMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetActionMappingByName_OutMappings) == 0x0000C0, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetActionMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Get_Item_2) == 0x0000D0, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Get_Item_3) == 0x0000F8, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Length_ReturnValue) == 0x000120, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Length_ReturnValue_1) == 0x000124, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Less_IntInt_ReturnValue) == 0x000128, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Less_IntInt_ReturnValue_1) == 0x000129, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Length_ReturnValue_2) == 0x00012C, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Length_ReturnValue_3) == 0x000130, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Less_IntInt_ReturnValue_2) == 0x000134, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Less_IntInt_ReturnValue_3) == 0x000135, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetInputSettings_ReturnValue_6) == 0x000138, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetInputSettings_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetDefaultAxisMappings_ReturnValue) == 0x000140, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetDefaultAxisMappings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_GetDefaultActionMappings_ReturnValue) == 0x000150, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_GetDefaultActionMappings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Get_Item_4) == 0x000160, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Get_Item_5) == 0x000188, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Length_ReturnValue_4) == 0x0001B0, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Array_Length_ReturnValue_5) == 0x0001B4, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Less_IntInt_ReturnValue_4) == 0x0001B8, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_ResetKeybindings, CallFunc_Less_IntInt_ReturnValue_5) == 0x0001B9, "Member 'WBP_Keybinds_C_ResetKeybindings::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");

// Function WBP_Keybinds.WBP_Keybinds_C.SaveDefaultBindings
// 0x0130 (0x0130 - 0x0000)
struct WBP_Keybinds_C_SaveDefaultBindings final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue;             // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_1;           // 0x0038(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           CallFunc_GetAxisNames_AxisNames;                   // 0x0040(0x0010)(ReferenceParm)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_2;           // 0x0050(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FInputAxisKeyMapping>           CallFunc_GetAxisMappingByName_OutMappings;         // 0x0068(0x0010)(ReferenceParm)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputAxisKeyMapping                   CallFunc_Array_Get_Item_1;                         // 0x0080(0x0028)()
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputSettings*                         CallFunc_GetInputSettings_ReturnValue_3;           // 0x00B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FName>                           CallFunc_GetActionNames_ActionNames;               // 0x00C0(0x0010)(ReferenceParm)
	class FName                                   CallFunc_Array_Get_Item_2;                         // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FInputActionKeyMapping>         CallFunc_GetActionMappingByName_OutMappings;       // 0x00E0(0x0010)(ReferenceParm)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F1[0x7];                                       // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FInputActionKeyMapping                 CallFunc_Array_Get_Item_3;                         // 0x00F8(0x0028)()
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Keybinds_C_SaveDefaultBindings) == 0x000008, "Wrong alignment on WBP_Keybinds_C_SaveDefaultBindings");
static_assert(sizeof(WBP_Keybinds_C_SaveDefaultBindings) == 0x000130, "Wrong size on WBP_Keybinds_C_SaveDefaultBindings");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_Keybinds_C_SaveDefaultBindings::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_Keybinds_C_SaveDefaultBindings::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, Temp_int_Loop_Counter_Variable_1) == 0x00000C, "Member 'WBP_Keybinds_C_SaveDefaultBindings::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, Temp_int_Loop_Counter_Variable_2) == 0x000010, "Member 'WBP_Keybinds_C_SaveDefaultBindings::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Add_IntInt_ReturnValue_1) == 0x000014, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Add_IntInt_ReturnValue_2) == 0x000018, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, Temp_int_Array_Index_Variable_1) == 0x00001C, "Member 'WBP_Keybinds_C_SaveDefaultBindings::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, Temp_int_Array_Index_Variable_2) == 0x000020, "Member 'WBP_Keybinds_C_SaveDefaultBindings::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, Temp_int_Loop_Counter_Variable_3) == 0x000024, "Member 'WBP_Keybinds_C_SaveDefaultBindings::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Add_IntInt_ReturnValue_3) == 0x000028, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, Temp_int_Array_Index_Variable_3) == 0x00002C, "Member 'WBP_Keybinds_C_SaveDefaultBindings::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_GetInputSettings_ReturnValue) == 0x000030, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_GetInputSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_GetInputSettings_ReturnValue_1) == 0x000038, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_GetInputSettings_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_GetAxisNames_AxisNames) == 0x000040, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_GetAxisNames_AxisNames' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_GetInputSettings_ReturnValue_2) == 0x000050, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_GetInputSettings_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Get_Item) == 0x000058, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Length_ReturnValue) == 0x000060, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_GetAxisMappingByName_OutMappings) == 0x000068, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_GetAxisMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Less_IntInt_ReturnValue) == 0x000078, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Get_Item_1) == 0x000080, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Add_ReturnValue) == 0x0000A8, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Length_ReturnValue_1) == 0x0000AC, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_GetInputSettings_ReturnValue_3) == 0x0000B0, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_GetInputSettings_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Less_IntInt_ReturnValue_1) == 0x0000B8, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_GetActionNames_ActionNames) == 0x0000C0, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_GetActionNames_ActionNames' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Get_Item_2) == 0x0000D0, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Length_ReturnValue_2) == 0x0000D8, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_GetActionMappingByName_OutMappings) == 0x0000E0, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_GetActionMappingByName_OutMappings' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Less_IntInt_ReturnValue_2) == 0x0000F0, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Get_Item_3) == 0x0000F8, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Add_ReturnValue_1) == 0x000120, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Array_Length_ReturnValue_3) == 0x000124, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(WBP_Keybinds_C_SaveDefaultBindings, CallFunc_Less_IntInt_ReturnValue_3) == 0x000128, "Member 'WBP_Keybinds_C_SaveDefaultBindings::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");

}

