#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Reconnect

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Reconnect.WBP_Reconnect_C
// 0x0040 (0x0320 - 0x02E0)
class UWBP_Reconnect_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_0;                                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_20;                                          // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             NotificationMessage;                               // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_HardwareButton_C*                  WBP_HardwareButton;                                // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_HardwareButton_C*                  WBP_HardwareButton_1;                              // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 AntiCheatMessage;                                  // 0x0310(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void BndEvt__WBP_HardwareButton_K2Node_ComponentBoundEvent_0_OnClicked__DelegateSignature();
	void BndEvt__WBP_Reconnect_WBP_HardwareButton_1_K2Node_ComponentBoundEvent_1_OnClicked__DelegateSignature();
	void Construct();
	void ExecuteUbergraph_WBP_Reconnect(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Reconnect_C">();
	}
	static class UWBP_Reconnect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Reconnect_C>();
	}
};
static_assert(alignof(UWBP_Reconnect_C) == 0x000008, "Wrong alignment on UWBP_Reconnect_C");
static_assert(sizeof(UWBP_Reconnect_C) == 0x000320, "Wrong size on UWBP_Reconnect_C");
static_assert(offsetof(UWBP_Reconnect_C, UberGraphFrame) == 0x0002E0, "Member 'UWBP_Reconnect_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_Reconnect_C, Image_0) == 0x0002E8, "Member 'UWBP_Reconnect_C::Image_0' has a wrong offset!");
static_assert(offsetof(UWBP_Reconnect_C, Image_20) == 0x0002F0, "Member 'UWBP_Reconnect_C::Image_20' has a wrong offset!");
static_assert(offsetof(UWBP_Reconnect_C, NotificationMessage) == 0x0002F8, "Member 'UWBP_Reconnect_C::NotificationMessage' has a wrong offset!");
static_assert(offsetof(UWBP_Reconnect_C, WBP_HardwareButton) == 0x000300, "Member 'UWBP_Reconnect_C::WBP_HardwareButton' has a wrong offset!");
static_assert(offsetof(UWBP_Reconnect_C, WBP_HardwareButton_1) == 0x000308, "Member 'UWBP_Reconnect_C::WBP_HardwareButton_1' has a wrong offset!");
static_assert(offsetof(UWBP_Reconnect_C, AntiCheatMessage) == 0x000310, "Member 'UWBP_Reconnect_C::AntiCheatMessage' has a wrong offset!");

}

