#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_FadeOutScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_FadeOutScreen.WBP_FadeOutScreen_C
// 0x0010 (0x02F0 - 0x02E0)
class UWBP_FadeOutScreen_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeOutAnimation;                                  // 0x02E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void CustomEvent_0();
	void ExecuteUbergraph_WBP_FadeOutScreen(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_FadeOutScreen_C">();
	}
	static class UWBP_FadeOutScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_FadeOutScreen_C>();
	}
};
static_assert(alignof(UWBP_FadeOutScreen_C) == 0x000008, "Wrong alignment on UWBP_FadeOutScreen_C");
static_assert(sizeof(UWBP_FadeOutScreen_C) == 0x0002F0, "Wrong size on UWBP_FadeOutScreen_C");
static_assert(offsetof(UWBP_FadeOutScreen_C, UberGraphFrame) == 0x0002E0, "Member 'UWBP_FadeOutScreen_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_FadeOutScreen_C, FadeOutAnimation) == 0x0002E8, "Member 'UWBP_FadeOutScreen_C::FadeOutAnimation' has a wrong offset!");

}

